# Generated by Django 5.2.7 on 2025-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
                ('our_score', models.PositiveIntegerField(default=0)),
                ('opponent_score', models.PositiveIntegerField(default=0)),
                ('our_shots', models.PositiveIntegerField(default=0)),
                ('opponent_shots', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
