# Generated by Django 5.2.7 on 2025-10-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_opponent_score_p1_game_opponent_score_p2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opponent_shots_p1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent_shots_p2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent_shots_p3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='our_shots_p1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='our_shots_p2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='our_shots_p3',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
