# Generated by Django 5.2.7 on 2025-10-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_opponent_shots_p1_game_opponent_shots_p2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='boxplay_goals_against',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='boxplays',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='powerplay_goals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='powerplays',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
