# Generated by Django 5.2.7 on 2025-10-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestats',
            name='plus_minus',
            field=models.IntegerField(default=0),
        ),
    ]
